//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTests.MerchantService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MerchantService.IMerchantService")]
    public interface IMerchantService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseLoginInterface/Login", ReplyAction="http://tempuri.org/IBaseLoginInterface/LoginResponse")]
        string Login(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseLoginInterface/Login", ReplyAction="http://tempuri.org/IBaseLoginInterface/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseLoginInterface/RefreshTokenNoReturn", ReplyAction="http://tempuri.org/IBaseLoginInterface/RefreshTokenNoReturnResponse")]
        string RefreshTokenNoReturn(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseLoginInterface/RefreshTokenNoReturn", ReplyAction="http://tempuri.org/IBaseLoginInterface/RefreshTokenNoReturnResponse")]
        System.Threading.Tasks.Task<string> RefreshTokenNoReturnAsync(string parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMerchantServiceChannel : ServiceTests.MerchantService.IMerchantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MerchantServiceClient : System.ServiceModel.ClientBase<ServiceTests.MerchantService.IMerchantService>, ServiceTests.MerchantService.IMerchantService {
        
        public MerchantServiceClient() {
        }
        
        public MerchantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MerchantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MerchantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MerchantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string parameters) {
            return base.Channel.Login(parameters);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string parameters) {
            return base.Channel.LoginAsync(parameters);
        }
        
        public string RefreshTokenNoReturn(string parameters) {
            return base.Channel.RefreshTokenNoReturn(parameters);
        }
        
        public System.Threading.Tasks.Task<string> RefreshTokenNoReturnAsync(string parameters) {
            return base.Channel.RefreshTokenNoReturnAsync(parameters);
        }
    }
}
