//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationClient.CustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/Login", ReplyAction="http://tempuri.org/IBaseService/LoginResponse")]
        string Login(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/Login", ReplyAction="http://tempuri.org/IBaseService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/RefreshTokenNoReturn", ReplyAction="http://tempuri.org/IBaseService/RefreshTokenNoReturnResponse")]
        string RefreshTokenNoReturn(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseService/RefreshTokenNoReturn", ReplyAction="http://tempuri.org/IBaseService/RefreshTokenNoReturnResponse")]
        System.Threading.Tasks.Task<string> RefreshTokenNoReturnAsync(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/CustomerGet", ReplyAction="http://tempuri.org/ICustomerService/CustomerGetResponse")]
        string CustomerGet(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/CustomerGet", ReplyAction="http://tempuri.org/ICustomerService/CustomerGetResponse")]
        System.Threading.Tasks.Task<string> CustomerGetAsync(string parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : ApplicationClient.CustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<ApplicationClient.CustomerService.ICustomerService>, ApplicationClient.CustomerService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string parameters) {
            return base.Channel.Login(parameters);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string parameters) {
            return base.Channel.LoginAsync(parameters);
        }
        
        public string RefreshTokenNoReturn(string parameters) {
            return base.Channel.RefreshTokenNoReturn(parameters);
        }
        
        public System.Threading.Tasks.Task<string> RefreshTokenNoReturnAsync(string parameters) {
            return base.Channel.RefreshTokenNoReturnAsync(parameters);
        }
        
        public string CustomerGet(string parameters) {
            return base.Channel.CustomerGet(parameters);
        }
        
        public System.Threading.Tasks.Task<string> CustomerGetAsync(string parameters) {
            return base.Channel.CustomerGetAsync(parameters);
        }
    }
}
